CREATE TABLE PRODUTO (
	CODIGO INT PRIMARY KEY,
	NOME VARCHAR(100),
	PRECO DECIMAL (9,2),
	PESO DECIMAL(5,3)
);

insert into produto(codigo, nome, preco, peso)
values (1, 'Carro', 3000, 15.00 );
insert into produto(codigo, nome, preco, peso)
values (2, 'Mouse', 150, 0.30 );
insert into produto(codigo, nome, preco, peso)
values (3, 'HeadSeat', 230, 0.50 );
insert into produto(codigo, nome, preco, peso)
values (4, 'Monitor', 400, 1000 );
insert into produto(codigo, nome, preco, peso)
values (5, 'Torno', 20000, 45 );

CREATE TABLE CLIENTE (
	ID_CLIENTE INT,
	NMCLIENTE VARCHAR(100),
	NMCIDADE VARCHAR(100)
);

INSERT INTO CLIENTE (ID_CLIENTE, NMCLIENTE, NMCIDADE)
VALUES (1,'MARCOS', 'CAPIVARI DE BAIXO');
INSERT INTO CLIENTE (ID_CLIENTE, NMCLIENTE, NMCIDADE)
VALUES (2,'LORENZO', 'TUBARAO');
INSERT INTO CLIENTE (ID_CLIENTE, NMCLIENTE, NMCIDADE)
VALUES (3,'DAVI', 'LAGUNA');
INSERT INTO CLIENTE (ID_CLIENTE, NMCLIENTE, NMCIDADE)
VALUES (4,'FELIPE', 'BLUMENAU');
INSERT INTO CLIENTE (ID_CLIENTE, NMCLIENTE, NMCIDADE)
VALUES (5,'GUSTAVO', 'CRICIUMA');

ALTER TABLE CLIENTE ADD COLUMN EMAIL VARCHAR(200);
ALTER TABLE PRODUTO ADD COLUMN ESTOQUE INT;

UPDATE TABLE CLIENTE SET CIDADE = 'LAGUNA' WHERE ID_CLIENTE = 1;
UPDATE TABLE PRODUTO SET PRECO = 5000 WHERE PESO > 10;

DELETE FROM PRODUTO WHERE CODIGO = 1;
DELETE FROM CLIENTE WHERE NMCIDADE = 'CRICIUMA';

SELECT * FROM PRODUTO ORDER BY PRECO;
SELECT * FROM CLIENTE ORDER BY NMCLIENTE DESC;

SELECT SUM(PRECO) FROM PRODUTO;

SELECT NMCIDADE, COUNT(*) FROM CLIENTE GROUP BY NMCIDADE;